import { Container, Theme } from '@radix-ui/themes'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Provider as AuthProvider } from './auth/Provider'

import '@radix-ui/themes/styles.css'
import 'react-loading-skeleton/dist/skeleton.css'
import './theme-config.css'
import './globals.css'
import { NavBar } from '@/app/components'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: 'Issue Tracker App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${inter.variable}`}>
          <Theme accentColor="blue" radius="small">
            <NavBar />
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </body>
      </AuthProvider>
    </html>
  )
}
